// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_QML_View)
QT_DECLARE_EXTERN_RESOURCE(qmake_QML_View)
QT_DECLARE_EXTERN_RESOURCE(QML_View_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_QML_View)

class QML_ViewPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QML_ViewPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_QML_View)
QT_KEEP_RESOURCE(qmlcache_QML_View)
QT_KEEP_RESOURCE(qmake_QML_View)
QT_KEEP_RESOURCE(QML_View_raw_qml_0)
    }
};



#include "QML_Viewplugin_QML_ViewPlugin.moc"
