### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(QML_ViewContent)
add_subdirectory(QML_View)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    QML_ViewContentplugin
    QML_Viewplugin)